#' Conversion from Mathematica to R
#'
#' Few adjustments to the data generated by Mathematica, for easy handling in R.
#'
#' @param data The dataset
#' @param numerics What columns are to be considered numeric in R
#' @param digits To what digit to round numerical values?
#'
#' @export

mathematica2r <- function(data, numerics, digits = 4) {

  library(tidyverse)

  data %>%
    mutate_if(~ any(.x == "True"), ~ .x == "True") %>%
    mutate_at(numerics, ~ round(as.numeric(as.character(.x)), digits))

}
